### PR TITLE
Add BitBucket SSH MAC configuration

### PR DESCRIPTION
**Pull request by nMustaki**

### CODE REVIEW

**Comment by stribika** [comment]
Can you change the host name to bitbucket's name?

**Comment by vszakats** [comment]
`hmac-ripemd160` can be used with `bitbucket.org` of the list of safe MACs.

**Comment by vszakats** [comment]
Here's `bitbucket.org`'s full list:
`hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160,hmac-ripemd160@openssh.com,hmac-sha1-96,hmac-md5-96`

**Comment by nMustaki** [comment]
Thanks for catching the typo !
I tried the MACs list you found, but it's not working for me, I get a "no
matching mac found" error when trying to push. Is it only me ?

Thanks
Nathan



--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Comment by nMustaki** [comment]
That was only me, sorry for spamming you...
In the MACs list, is there a "least terrible" algo than the others ?

Thanks again !


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Comment by stribika** [comment]
If it's these MACs or death, I'd use hmac-ripemd160,hmac-ripemd160. SHA1 is broken, MD5 is more broken, and UMAC-64 is too short.

**Comment by nMustaki** [comment]
Thanks !


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Pull request merged**
